import { Geist, Geist_Mono, Cabin_Sketch, Quicksand } from "next/font/google";
import "./globals.css";


// clerk
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
   weight: ["300", "400", "500", "600", "700"],
})

const cabinSketch = Cabin_Sketch({
  variable: "--font-cabin-sketch",
  subsets: ["latin"],
  weight: ["400", "700"]
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "feather finders - birdwatcher social media app",
  description: "Generated by birdwatchers for birdwatchers - a way to share bird sightings with friends, and to explore bird sightings across the world",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({children}){
 return (
    <ClerkProvider
      signUpForceRedirectUrl="/create-profile"
      signInForceRedirectUrl="/posts">
      <html lang="en">
        <body className={`${cabinSketch.variable} ${quicksand.variable} antialiased bg-sky-500`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16 ">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}

  
 
